### PR TITLE
Fix/update readme.md

### PR DESCRIPTION
**Pull request by xygyo77**

### CODE REVIEW

**Review by takam5f2 — APPROVED** [review]
LGTM

**Comment by takam5f2** [comment]
@nabetetsu  
Could you check the PR? If you are busy on other task, I'd like to check it.

**Review by nabetetsu — APPROVED** [review]
LGTM :+1:

**Comment by nabetetsu** [comment]
@takam5f2 Could you update the review status?

**Review by takam5f2 — APPROVED** [review]

**Pull request merged**
