### PR TITLE
refactor: reduce install warnings and delete unnecessary msgs

### PR DESCRIPTION
**Pull request by nabetetsu**

### CODE REVIEW

**Comment by nabetetsu** [comment]
I also deleted test_depend for caret_lint_common at this moment.

**Comment by xygyo77** [comment]
Do you know how to fix the pre-commit.ci error?

**Comment by nabetetsu** [comment]
> Do you know how to fix the pre-commit.ci error?

Please let me check ament_lint_common instead of caret_lint_common.
If it doesn't work, I will consider about reverting the changes at this moment.

**Comment by nabetetsu** [comment]
@xygyo77 The test results ditd not change before and after these commit, so perhaps this error is not caused by the commit.
after: https://github.com/tier4/tilde_lite/actions/runs/4049362901/jobs/6965638889#step:37:719
before: https://github.com/tier4/tilde_lite/actions/runs/4029136028/jobs/6926717350

**Review by xygyo77 — APPROVED** [review]

**Review by y-okumura-isp — APPROVED** [review]
LGTM

**Pull request merged**
